/* Generated by buildtables.py */

static void (*optable[256])() = {
/*         |    0    |    1    |    2    |    3    |    4    |    5    |    6    |    7    |    8    |    9    |    A    |    B    |    C    |    D    |    E    |    F    |     */
/* 0 */      brk_00,   ora_01,      nop,      nop,   tsb_04,   ora_05,  aslm_06,  rmb0_07,   php_08,   ora_09,  asla_0a,      nop,   tsb_0c,   ora_0d,  aslm_0e,  bbr0_0f, /* 0 */
/* 1 */      bpl_10,   ora_11,   ora_12,      nop,   trb_14,   ora_15,  aslm_16,  rmb1_17,   clc_18,   ora_19,  inca_1a,      nop,   trb_1c,   ora_1d,  aslm_1e,  bbr1_1f, /* 1 */
/* 2 */      jsr_20,   and_21,      nop,      nop,   bit_24,   and_25,  rolm_26,  rmb2_27,   plp_28,   and_29,  rola_2a,      nop,   bit_2c,   and_2d,  rolm_2e,  bbr2_2f, /* 2 */
/* 3 */      bmi_30,   and_31,   and_32,      nop,   bit_34,   and_35,  rolm_36,  rmb3_37,   sec_38,   and_39,  deca_3a,      nop,   bit_3c,   and_3d,  rolm_3e,  bbr3_3f, /* 3 */
/* 4 */      rti_40,   eor_41,      nop,      nop,      nop,   eor_45,  lsrm_46,  rmb4_47,   pha_48,   eor_49,  lsra_4a,      nop,   jmp_4c,   eor_4d,  lsrm_4e,  bbr4_4f, /* 4 */
/* 5 */      bvc_50,   eor_51,   eor_52,      nop,      nop,   eor_55,  lsrm_56,  rmb5_57,   cli_58,   eor_59,   phy_5a,      nop,      nop,   eor_5d,  lsrm_5e,  bbr5_5f, /* 5 */
/* 6 */      rts_60,  adcx_61,      nop,      nop,   stz_64,  adcx_65,  rorm_66,  rmb6_67,   pla_68,  adcx_69,  rora_6a,      nop,   jmp_6c,  adcx_6d,  rorm_6e,  bbr6_6f, /* 6 */
/* 7 */      bvs_70,  adcx_71,  adcx_72,      nop,   stz_74,  adcx_75,  rorm_76,  rmb7_77,   sei_78,  adcx_79,   ply_7a,      nop,   jmp_7c,  adcx_7d,  rorm_7e,  bbr7_7f, /* 7 */
/* 8 */      bra_80,   sta_81,      nop,      nop,   sty_84,   sta_85,   stx_86,  smb0_87,   dey_88,   bit_89,   txa_8a,      nop,   sty_8c,   sta_8d,   stx_8e,  bbs0_8f, /* 8 */
/* 9 */      bcc_90,   sta_91,   sta_92,      nop,   sty_94,   sta_95,   stx_96,  smb1_97,   tya_98,   sta_99,   txs_9a,      nop,   stz_9c,   sta_9d,   stz_9e,  bbs1_9f, /* 9 */
/* A */      ldy_a0,   lda_a1,   ldx_a2,      nop,   ldy_a4,   lda_a5,   ldx_a6,  smb2_a7,   tay_a8,   lda_a9,   tax_aa,      nop,   ldy_ac,   lda_ad,   ldx_ae,  bbs2_af, /* A */
/* B */      bcs_b0,   lda_b1,   lda_b2,      nop,   ldy_b4,   lda_b5,   ldx_b6,  smb3_b7,   clv_b8,   lda_b9,   tsx_ba,      nop,   ldy_bc,   lda_bd,   ldx_be,  bbs3_bf, /* B */
/* C */      cpy_c0,   cmp_c1,      nop,      nop,   cpy_c4,   cmp_c5,  decm_c6,  smb4_c7,   iny_c8,   cmp_c9,   dex_ca,   wai_cb,   cpy_cc,   cmp_cd,  decm_ce,  bbs4_cf, /* C */
/* D */      bne_d0,   cmp_d1,   cmp_d2,      nop,      nop,   cmp_d5,  decm_d6,  smb5_d7,   cld_d8,   cmp_d9,   phx_da,   dbg_db,      nop,   cmp_dd,  decm_de,  bbs5_df, /* D */
/* E */      cpx_e0,  sbcx_e1,      nop,      nop,   cpx_e4,  sbcx_e5,  incm_e6,  smb6_e7,   inx_e8,  sbcx_e9,      nop,      nop,   cpx_ec,  sbcx_ed,  incm_ee,  bbs6_ef, /* E */
/* F */      beq_f0,  sbcx_f1,  sbcx_f2,      nop,      nop,  sbcx_f5,  incm_f6,  smb7_f7,   sed_f8,  sbcx_f9,   plx_fa,      nop,      nop,  sbcx_fd,  incm_fe,  bbs7_ff  /* F */
};
